export default {
  app: { description: 'Vehicle telemetry, visualization & programmability' },
  nav: { dashboard: 'Dashboard', vehicles: 'Vehicles', dashboards: 'Dashboards', hooks: 'Hooks', devices: 'Devices', settings: 'Settings', signOut: 'Sign out' },
  common: { online: 'Online', parked: 'Parked', stale: 'Parked / stale', close: 'Close', save: 'Save', cancel: 'Cancel', delete: 'Delete', loading: 'Loading…', never: 'Never', updated: 'Updated', error: 'Something went wrong', type: 'Type', title: 'Title' },
  auth: {
    welcome: 'Welcome back', firstIgnition: 'First ignition', signInTitle: 'Sign in to your garage', registerTitle: 'Create your account',
    signInHint: 'Your live fleet is waiting.', registerHint: 'The first account becomes the system administrator.',
    displayName: 'Display name', email: 'Email', password: 'Password', signIn: 'Sign in', create: 'Create account', connecting: 'Connecting…',
    switchRegister: 'New installation? Create an account', switchLogin: 'Already set up? Sign in',
    eyebrow: 'Connected vehicle · your infrastructure', headline: 'Your vehicle produces data.', headlineAccent: 'You decide what it does.', privacy: 'Private by default, programmable by design.',
  },
  dashboard: {
    live: 'Live telemetry', morning: 'Good morning.', evening: 'Good evening.', quiet: 'Your garage is quiet', quietHint: 'Add a vehicle, then enroll the simulator or a tracker.', addFirst: 'Add your first vehicle',
    battery: 'Traction battery', power: 'Power', charging: 'Charging', active: 'Active', no: 'No', speed: 'Road speed', signal: 'Signal', connection: 'Tracker connection', pastDay: 'Past 24 hours', batteryState: 'Battery state', explore: 'Explore history →', awaiting: 'Awaiting first telemetry', soc: 'Battery SOC', loadError: 'Could not load vehicles',
  },
  vehicles: { garage: 'Garage', title: 'Vehicles', add: '+ Add vehicle', noVehicles: 'No vehicles yet', noVehiclesHint: 'Create one to begin collecting telemetry.', create: 'Create vehicle', name: 'Name', manufacturer: 'Manufacturer', model: 'Model', year: 'Year', propulsion: 'Propulsion', capacity: 'Battery capacity (kWh)', profile: 'Vehicle profile', color: 'Color', profileExperimental: 'C-Zero / i-MiEV / iOn (experimental)', none: 'None', yearUnknown: 'Year unknown', history: 'History', tracker: 'Tracker', speed: 'Speed' },
  history: { eyebrow: 'Telemetry explorer', title: 'History', metric: 'Metric', range: 'Range', day: '24 hours', week: '7 days', month: '30 days', samples: '{count} source samples', route: 'Route', noData: 'No telemetry in this range.' },
  settings: { eyebrow: 'Preferences', title: 'Settings', appearance: 'Appearance', theme: 'Theme', language: 'Language', light: 'Light', dark: 'Dark', auto: 'Auto', english: 'English', french: 'Français', saved: 'Preferences are saved in this browser.', account: 'Account', sessionHint: 'Browser sessions use secure server-side cookies. Device credentials cannot access this account.', changePassword: 'Change password', currentPassword: 'Current password', newPassword: 'New password', passwordChanged: 'Password changed; other sessions were revoked.', activeSessions: 'Active sessions', currentSession: 'This session', unknownClient: 'Unknown client', revokeSession: 'Revoke', diagnostics: 'System diagnostics', version: 'Version', database: 'Database', workers: 'Workers', pendingJobs: 'Pending jobs', failedJobs: 'Failed jobs', hookFailures: 'Hook failures', staleDevices: 'Stale devices' },
  devices: { eyebrow: 'Trackers', title: 'Devices', add: 'Add tracker', name: 'Name', vehicle: 'Vehicle', status: 'Status', version: 'Agent version', lastSeen: 'Last seen', actions: 'Actions', enrollTitle: 'Enroll a tracker', commandHint: 'Run this one-time command on the Raspberry Pi. The token expires and is never the permanent credential.', copy: 'Copy command', copied: 'Copied', revoke: 'Revoke', revoked: 'Revoked', rotate: 'Rotate credential', noDevices: 'No trackers enrolled.' },
  hooks: { eyebrow: 'Programmability', title: 'Python hooks', new: '+ New hook', trusted: 'Privileged code', trustedHint: 'Anyone who can edit hooks can execute privileged Python in the worker environment.', name: 'Name', description: 'Description', enabled: 'Enabled', vehicle: 'Vehicle filter', allVehicles: 'All vehicles', timeout: 'Timeout (seconds)', source: 'Python source', test: 'Test with telemetry', dryRun: 'Dry run', sideEffectWarning: 'Test execution can make real network requests. Use ctx.dry_run in your code to suppress side effects.', executions: 'Execution history', noExecutions: 'No executions yet', status: 'Status', duration: 'Duration', logs: 'Logs', revision: 'Revision {revision}', revisions: 'Revision history', restoreRevision: 'Restore revision {revision}', secrets: 'Secrets', secretsHint: 'Encrypted values are write-only and shown masked after creation.', createVehicleFirst: 'Create a vehicle first', noTelemetry: 'No historical telemetry is available' },
  dashboards: { eyebrow: 'Workspace', title: 'Custom dashboards', defaultName: 'My dashboard', addWidget: '+ Add widget', save: 'Save layout', empty: 'Create a dashboard to arrange live widgets.', metricCard: 'Metric card', batteryGauge: 'Battery gauge', positionMap: 'Vehicle position map', timeSeries: 'Time-series chart', multiSeries: 'Multi-series chart', metrics: 'Metrics (comma separated)', timeRange: 'Time range', onlineStatus: 'Online status', deviceHealth: 'Device health', hookActivity: 'Latest hook activity' },
}
