export default {
  app: { description: 'Vehicle telemetry, visualization & programmability' },
  nav: { dashboard: 'Dashboard', vehicles: 'Vehicles', dashboards: 'Dashboards', hooks: 'Hooks', devices: 'Devices', settings: 'Settings', signOut: 'Sign out', workspace: 'Workspace', system: 'System', platformReady: 'Platform ready', platformReadyHint: 'Telemetry services healthy', controlCenter: 'Vehicle control center', secureConnection: 'Encrypted telemetry link', telemetryNode: 'Telemetry node' },
  common: { online: 'Online', parked: 'Parked', stale: 'Parked / stale', close: 'Close', save: 'Save', cancel: 'Cancel', delete: 'Delete', loading: 'Loading…', never: 'Never', updated: 'Updated', error: 'Something went wrong', type: 'Type', title: 'Title' },
  auth: {
    welcome: 'Account access', firstIgnition: 'Initial setup', signInTitle: 'Sign in to VehiNode', registerTitle: 'Create the administrator account',
    signInHint: 'Enter your account details.', registerHint: 'The first account becomes the system administrator.',
    displayName: 'Display name', email: 'Email', password: 'Password', signIn: 'Sign in', create: 'Create account', connecting: 'Connecting…',
    switchRegister: 'Create the initial administrator', switchLogin: 'Administrator already created? Sign in',
    instance: 'Self-hosted instance', workspaceTitle: 'Vehicle telemetry workspace', workspaceHint: 'Use your server account to inspect vehicles, history, trackers and hooks.', openSource: 'Open-source software · operated by you',
  },
  dashboard: {
    live: 'Live telemetry', morning: 'Good morning.', evening: 'Good evening.', quiet: 'Your garage is quiet', quietHint: 'Add a vehicle, then enroll the simulator or a tracker.', addFirst: 'Add your first vehicle',
    battery: 'Traction battery', power: 'Power', charging: 'Charging', active: 'Active', no: 'No', speed: 'Road speed', signal: 'Signal', connection: 'Tracker connection', pastDay: 'Past 24 hours', batteryState: 'Battery state', explore: 'Explore history →', awaiting: 'Awaiting first telemetry', soc: 'Battery SOC', loadError: 'Could not load vehicles',
    overview: 'Fleet overview', tracked: 'Tracked vehicles', connected: 'Connected now', averageSoc: 'Average battery', chargingNow: 'Charging now', liveWorkspace: 'Live vehicle workspace', chooseVehicle: 'Choose a vehicle to inspect', latestPosition: 'Latest reported position', noPosition: 'Waiting for a valid GNSS fix', telemetry: 'Current telemetry', energyFlow: 'Energy flow', lastContact: 'Last contact', batteryLevel: 'Battery level', vehiclesCount: '{count} configured', onlineCount: '{count} reporting', chargingCount: '{count} active', fleetReady: 'Telemetry at a glance', position: 'Position', validFix: 'Valid fix', awaitingFix: 'Awaiting fix', notCharging: 'Not charging', sampleCount: '{count} samples', liveStream: { connecting: 'Connecting live data', open: 'Live updates', reconnecting: 'Reconnecting live data' }, batteryTrace: 'Battery trace', garageSummary: '{online} of {count} vehicles reporting · {charging} charging', mapAndRoute: 'Position and recent route',
  },
  vehicles: { garage: 'Your garage', title: 'Vehicles', add: 'Add vehicle', noVehicles: 'No vehicles yet', noVehiclesHint: 'Create one to begin collecting telemetry.', create: 'Create vehicle', name: 'Name', manufacturer: 'Manufacturer', model: 'Model', year: 'Year', propulsion: 'Propulsion', capacity: 'Battery capacity (kWh)', profile: 'Vehicle profile', color: 'Color', profileExperimental: 'C-Zero / i-MiEV / iOn (experimental)', none: 'None', yearUnknown: 'Year unknown', history: 'History', tracker: 'Tracker', speed: 'Speed', overview: 'Vehicles overview', totalVehicles: 'Total vehicles', onlineVehicles: 'Connected vehicles', averageBattery: 'Average battery', listTitle: 'Garage roster', search: 'Search vehicles…', all: 'All', onlineOnly: 'Online', parkedOnly: 'Parked', batteryLevel: 'Battery level', currentSpeed: 'Current speed', lastContact: 'Last contact', noMatch: 'No vehicles match this search.', newRecord: 'New vehicle', registered: 'Registered', transmitting: 'Transmitting', fleetCharge: 'Average charge', registerHint: 'Select a vehicle to inspect its latest state', manifest: 'Vehicle list', selectedRecord: 'Selected vehicle', noProfile: 'No profile', summary: '{count} vehicles · {online} reporting · {soc}% average charge' },
  history: { eyebrow: 'Telemetry explorer', title: 'History', metric: 'Metric', range: 'Range', day: '24 hours', week: '7 days', month: '30 days', samples: '{count} source samples', route: 'Route', routeStart: 'Route start', latestPosition: 'Latest position', mapLoading: 'Loading map', mapUnavailable: 'Map tiles unavailable', noData: 'No telemetry in this range.' },
  settings: { eyebrow: 'Preferences', title: 'Settings', appearance: 'Appearance', theme: 'Theme', language: 'Language', light: 'Light', dark: 'Dark', auto: 'Auto', english: 'English', french: 'Français', saved: 'Preferences are saved in this browser.', account: 'Account', sessionHint: 'Browser sessions use secure server-side cookies. Device credentials cannot access this account.', changePassword: 'Change password', currentPassword: 'Current password', newPassword: 'New password', passwordChanged: 'Password changed; other sessions were revoked.', activeSessions: 'Active sessions', currentSession: 'This session', unknownClient: 'Unknown client', revokeSession: 'Revoke', diagnostics: 'System diagnostics', version: 'Version', database: 'Database', workers: 'Workers', pendingJobs: 'Pending jobs', failedJobs: 'Failed jobs', hookFailures: 'Hook failures', staleDevices: 'Stale devices' },
  devices: { eyebrow: 'Trackers', title: 'Devices', add: 'Add tracker', name: 'Name', vehicle: 'Vehicle', status: 'Status', version: 'Agent version', lastSeen: 'Last seen', actions: 'Actions', enrollTitle: 'Enroll a tracker', commandHint: 'Run this one-time command on the Raspberry Pi. The token expires and is never the permanent credential.', copy: 'Copy command', copied: 'Copied', revoke: 'Revoke', revoked: 'Revoked', rotate: 'Rotate credential', noDevices: 'No trackers enrolled.', overview: 'Tracker overview', total: 'Enrolled trackers', connected: 'Connected trackers', versions: 'Agent versions', hardware: 'Hardware', credentialReady: 'New credential — copy it now', credentialHint: 'This value will not be shown again.', summary: '{online} of {count} trackers reporting · {versions} agent versions', roster: 'Tracker roster' },
  hooks: { eyebrow: 'Programmability', title: 'Python hooks', new: '+ New hook', trusted: 'Privileged code', trustedHint: 'Anyone who can edit hooks can execute privileged Python in the worker environment.', name: 'Name', description: 'Description', enabled: 'Enabled', vehicle: 'Vehicle filter', allVehicles: 'All vehicles', timeout: 'Timeout (seconds)', source: 'Python source', test: 'Test with telemetry', dryRun: 'Dry run', sideEffectWarning: 'Test execution can make real network requests. Use ctx.dry_run in your code to suppress side effects.', executions: 'Execution history', noExecutions: 'No executions yet', status: 'Status', duration: 'Duration', logs: 'Logs', revision: 'Revision {revision}', revisions: 'Revision history', restoreRevision: 'Restore revision {revision}', secrets: 'Secrets', secretsHint: 'Encrypted values are write-only and shown masked after creation.', createVehicleFirst: 'Create a vehicle first', noTelemetry: 'No historical telemetry is available' },
  dashboards: { eyebrow: 'Workspace', title: 'Custom dashboards', defaultName: 'My dashboard', addWidget: '+ Add widget', save: 'Save layout', empty: 'Create a dashboard to arrange live widgets.', metricCard: 'Metric card', batteryGauge: 'Battery gauge', positionMap: 'Vehicle position map', timeSeries: 'Time-series chart', multiSeries: 'Multi-series chart', metrics: 'Metrics (comma separated)', timeRange: 'Time range', onlineStatus: 'Online status', deviceHealth: 'Device health', hookActivity: 'Latest hook activity', canvasHint: 'Drag and resize widgets to shape your telemetry workspace', widgetCount: '{count} widgets' },
}
