export default {
  app: { description: 'Télémétrie, visualisation et programmation automobile' },
  nav: { dashboard: 'Tableau de bord', vehicles: 'Véhicules', dashboards: 'Tableaux', hooks: 'Hooks', devices: 'Traceurs', settings: 'Réglages', signOut: 'Se déconnecter', workspace: 'Espace de travail', system: 'Système', platformReady: 'Plateforme prête', platformReadyHint: 'Services de télémétrie sains', controlCenter: 'Centre de contrôle véhicule', secureConnection: 'Liaison télémétrique chiffrée', telemetryNode: 'Nœud télémétrique' },
  common: { online: 'En ligne', parked: 'Stationné', stale: 'Stationné / ancien', close: 'Fermer', save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', loading: 'Chargement…', never: 'Jamais', updated: 'Mis à jour', error: 'Une erreur est survenue', type: 'Type', title: 'Titre' },
  auth: {
    welcome: 'Bon retour', firstIgnition: 'Premier démarrage', signInTitle: 'Connectez-vous à votre garage', registerTitle: 'Créez votre compte',
    signInHint: 'Votre flotte en direct vous attend.', registerHint: 'Le premier compte devient administrateur système.',
    displayName: 'Nom affiché', email: 'E-mail', password: 'Mot de passe', signIn: 'Se connecter', create: 'Créer le compte', connecting: 'Connexion…',
    switchRegister: 'Nouvelle installation ? Créer un compte', switchLogin: 'Déjà configuré ? Se connecter',
    eyebrow: 'Véhicule connecté · votre infrastructure', headline: 'Votre véhicule produit des données.', headlineAccent: 'Vous décidez de leur usage.', privacy: 'Privé par défaut, programmable par conception.',
  },
  dashboard: {
    live: 'Télémétrie en direct', morning: 'Bonjour.', evening: 'Bonsoir.', quiet: 'Votre garage est silencieux', quietHint: 'Ajoutez un véhicule, puis inscrivez le simulateur ou un traceur.', addFirst: 'Ajouter votre premier véhicule',
    battery: 'Batterie de traction', power: 'Puissance', charging: 'Recharge', active: 'Active', no: 'Non', speed: 'Vitesse', signal: 'Signal', connection: 'Connexion du traceur', pastDay: 'Dernières 24 heures', batteryState: 'État de la batterie', explore: 'Explorer l’historique →', awaiting: 'En attente de télémétrie', soc: 'Charge batterie', loadError: 'Impossible de charger les véhicules',
    overview: 'Aperçu de la flotte', tracked: 'Véhicules suivis', connected: 'Connectés maintenant', averageSoc: 'Batterie moyenne', chargingNow: 'En recharge', liveWorkspace: 'Espace véhicule en direct', chooseVehicle: 'Choisissez un véhicule à examiner', latestPosition: 'Dernière position reçue', noPosition: 'En attente d’une position GNSS valide', telemetry: 'Télémétrie actuelle', energyFlow: 'Flux d’énergie', lastContact: 'Dernier contact', batteryLevel: 'Niveau de batterie', vehiclesCount: '{count} configurés', onlineCount: '{count} transmettent', chargingCount: '{count} actifs', fleetReady: 'La télémétrie en un coup d’œil', position: 'Position', validFix: 'Fix valide', awaitingFix: 'Fix en attente', notCharging: 'Hors recharge', sampleCount: '{count} échantillons', refreshCycle: 'Actualisation 15 s', batteryTrace: 'Courbe de batterie',
  },
  vehicles: { garage: 'Garage', title: 'Véhicules', add: 'Ajouter un véhicule', noVehicles: 'Aucun véhicule', noVehiclesHint: 'Créez-en un pour commencer la collecte.', create: 'Créer le véhicule', name: 'Nom', manufacturer: 'Constructeur', model: 'Modèle', year: 'Année', propulsion: 'Motorisation', capacity: 'Capacité batterie (kWh)', profile: 'Profil véhicule', color: 'Couleur', profileExperimental: 'C-Zero / i-MiEV / iOn (expérimental)', none: 'Aucun', yearUnknown: 'Année inconnue', history: 'Historique', tracker: 'Traceur', speed: 'Vitesse', overview: 'Aperçu des véhicules', totalVehicles: 'Total véhicules', onlineVehicles: 'Véhicules connectés', averageBattery: 'Batterie moyenne', listTitle: 'Liste des véhicules', search: 'Rechercher un véhicule…', all: 'Tous', onlineOnly: 'En ligne', parkedOnly: 'Stationnés', batteryLevel: 'Niveau de batterie', currentSpeed: 'Vitesse actuelle', lastContact: 'Dernier contact', noMatch: 'Aucun véhicule ne correspond à cette recherche.', newRecord: 'Nouveau véhicule', registered: 'Enregistrés', transmitting: 'En transmission', fleetCharge: 'Charge moyenne', registerHint: 'Sélectionnez un véhicule pour voir son dernier état', manifest: 'Liste des véhicules', selectedRecord: 'Véhicule sélectionné', noProfile: 'Aucun profil' },
  history: { eyebrow: 'Explorateur de télémétrie', title: 'Historique', metric: 'Métrique', range: 'Période', day: '24 heures', week: '7 jours', month: '30 jours', samples: '{count} échantillons source', route: 'Trajet', noData: 'Aucune télémétrie sur cette période.' },
  settings: { eyebrow: 'Préférences', title: 'Réglages', appearance: 'Apparence', theme: 'Thème', language: 'Langue', light: 'Clair', dark: 'Sombre', auto: 'Auto', english: 'English', french: 'Français', saved: 'Les préférences sont enregistrées dans ce navigateur.', account: 'Compte', sessionHint: 'Les sessions utilisent des cookies sécurisés côté serveur. Les identifiants appareil ne donnent pas accès à ce compte.', changePassword: 'Changer le mot de passe', currentPassword: 'Mot de passe actuel', newPassword: 'Nouveau mot de passe', passwordChanged: 'Mot de passe modifié ; les autres sessions ont été révoquées.', activeSessions: 'Sessions actives', currentSession: 'Cette session', unknownClient: 'Client inconnu', revokeSession: 'Révoquer', diagnostics: 'Diagnostic système', version: 'Version', database: 'Base de données', workers: 'Workers', pendingJobs: 'Jobs en attente', failedJobs: 'Jobs échoués', hookFailures: 'Échecs de hooks', staleDevices: 'Traceurs anciens' },
  devices: { eyebrow: 'Traceurs', title: 'Appareils', add: 'Ajouter un traceur', name: 'Nom', vehicle: 'Véhicule', status: 'État', version: 'Version agent', lastSeen: 'Dernier contact', actions: 'Actions', enrollTitle: 'Inscrire un traceur', commandHint: 'Exécutez cette commande unique sur le Raspberry Pi. Le jeton expire et ne devient jamais l’identifiant permanent.', copy: 'Copier la commande', copied: 'Copié', revoke: 'Révoquer', revoked: 'Révoqué', rotate: 'Renouveler l’identifiant', noDevices: 'Aucun traceur inscrit.', overview: 'Aperçu des traceurs', total: 'Traceurs inscrits', connected: 'Traceurs connectés', versions: 'Versions agent', hardware: 'Matériel', credentialReady: 'Nouvel identifiant — copiez-le maintenant', credentialHint: 'Cette valeur ne sera plus affichée.' },
  hooks: { eyebrow: 'Programmabilité', title: 'Hooks Python', new: '+ Nouveau hook', trusted: 'Code privilégié', trustedHint: 'Toute personne pouvant modifier les hooks peut exécuter du Python privilégié dans le worker.', name: 'Nom', description: 'Description', enabled: 'Activé', vehicle: 'Filtre véhicule', allVehicles: 'Tous les véhicules', timeout: 'Délai (secondes)', source: 'Source Python', test: 'Tester avec une télémétrie', dryRun: 'Simulation', sideEffectWarning: 'Le test peut effectuer de vraies requêtes réseau. Utilisez ctx.dry_run pour supprimer les effets.', executions: 'Historique d’exécution', noExecutions: 'Aucune exécution', status: 'État', duration: 'Durée', logs: 'Journaux', revision: 'Révision {revision}', revisions: 'Historique des révisions', restoreRevision: 'Restaurer la révision {revision}', secrets: 'Secrets', secretsHint: 'Les valeurs chiffrées sont non lisibles et restent masquées après leur création.', createVehicleFirst: 'Créez d’abord un véhicule', noTelemetry: 'Aucune télémétrie historique disponible' },
  dashboards: { eyebrow: 'Espace de travail', title: 'Tableaux personnalisés', defaultName: 'Mon tableau', addWidget: '+ Ajouter un widget', save: 'Enregistrer la disposition', empty: 'Créez un tableau pour organiser les widgets.', metricCard: 'Carte métrique', batteryGauge: 'Jauge batterie', positionMap: 'Carte de position', timeSeries: 'Courbe temporelle', multiSeries: 'Courbe multi-séries', metrics: 'Métriques (séparées par virgule)', timeRange: 'Période', onlineStatus: 'État en ligne', deviceHealth: 'Santé du traceur', hookActivity: 'Dernière activité hook', canvasHint: 'Déplacez et redimensionnez les widgets pour façonner votre espace télémétrique', widgetCount: '{count} widgets' },
}
