CONNECTOR_IMPLEMENTATION_PREFIX = "connector."
TESLAMATE_KIND = "teslamate.mqtt"
TESLAMATE_IMPLEMENTATION_ID = f"{CONNECTOR_IMPLEMENTATION_PREFIX}{TESLAMATE_KIND}"
TESLAMATE_MAPPING_PROFILE = "teslamate-mqtt-v1"
DEFAULT_MAPPING_PROFILES = {TESLAMATE_KIND: TESLAMATE_MAPPING_PROFILE}
MASKED_PASSWORD = "••••••••"
