<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { api } from '../api/client'
import type { History, Hook, HookExecution, HookRevision, Vehicle } from '../api/types'
import CodeEditor from '../components/CodeEditor.vue'

interface Secret {id:string;name:string;masked:string;created_at:string;updated_at:string}
const defaultSource=`# Runs after telemetry is safely stored.\nsoc = ctx.telemetry.metrics.get("battery.soc")\nif soc is not None and soc < 20:\n    ctx.log.warning("Battery is low", soc=soc)\n`
const {t}=useI18n();const hooks=ref<Hook[]>([]);const vehicles=ref<Vehicle[]>([]);const selectedId=ref('');const executions=ref<HookExecution[]>([]);const revisions=ref<HookRevision[]>([]);const error=ref('');const saved=ref(false);const testing=ref(false);const secrets=ref<Secret[]>([]);const secretName=ref('');const secretValue=ref('')
const form=ref({name:'',description:'',enabled:false,trigger_type:'telemetry.received',vehicle_id:null as string|null,source:defaultSource,timeout_seconds:10})
const selected=computed(()=>hooks.value.find(row=>row.id===selectedId.value))
async function load(){;[hooks.value,vehicles.value,secrets.value]=await Promise.all([api<Hook[]>('/hooks'),api<Vehicle[]>('/vehicles'),api<Secret[]>('/secrets')]);if(!selectedId.value&&hooks.value[0])select(hooks.value[0].id)}
function select(id:string){const hook=hooks.value.find(row=>row.id===id);if(!hook)return;selectedId.value=id;form.value={name:hook.name,description:hook.description,enabled:hook.enabled,trigger_type:hook.trigger_type,vehicle_id:hook.vehicle_id,source:hook.source,timeout_seconds:hook.timeout_seconds};void loadExecutions()}
function fresh(){selectedId.value='';executions.value=[];revisions.value=[];form.value={name:'',description:'',enabled:false,trigger_type:'telemetry.received',vehicle_id:null,source:defaultSource,timeout_seconds:10}}
async function save(){error.value='';try{const hook=await api<Hook>(selectedId.value?`/hooks/${selectedId.value}`:'/hooks',{method:selectedId.value?'PUT':'POST',body:JSON.stringify(form.value)});selectedId.value=hook.id;saved.value=true;await load();window.setTimeout(()=>saved.value=false,1500)}catch(reason){error.value=reason instanceof Error?reason.message:t('common.error')}}
async function loadExecutions(){if(selectedId.value){[executions.value,revisions.value]=await Promise.all([api<HookExecution[]>(`/hooks/${selectedId.value}/executions`),api<HookRevision[]>(`/hooks/${selectedId.value}/revisions`)])}}
async function restoreRevision(revision:number){if(!selectedId.value)return;const hook=await api<Hook>(`/hooks/${selectedId.value}/revisions/${revision}/restore`,{method:'POST'});await load();select(hook.id)}
async function testHook(){if(!selectedId.value)return;testing.value=true;try{const vehicleId=form.value.vehicle_id??vehicles.value[0]?.id;if(!vehicleId)throw new Error(t('hooks.createVehicleFirst'));const history=await api<History>(`/vehicles/${vehicleId}/history?max_points=20`);const telemetry=history.points.at(-1);if(!telemetry)throw new Error(t('hooks.noTelemetry'));await api(`/hooks/${selectedId.value}/test`,{method:'POST',body:JSON.stringify({telemetry_id:telemetry.id,dry_run:true})});await loadExecutions()}catch(reason){error.value=reason instanceof Error?reason.message:t('common.error')}finally{testing.value=false}}
async function storeSecret(){await api(`/secrets/${secretName.value}`,{method:'PUT',body:JSON.stringify({name:secretName.value,value:secretValue.value})});secretName.value='';secretValue.value='';secrets.value=await api<Secret[]>('/secrets')}
async function removeSecret(name:string){await api(`/secrets/${name}`,{method:'DELETE'});secrets.value=secrets.value.filter(row=>row.name!==name)}
onMounted(load)
</script>

<template>
  <div class="page">
    <header class="page-header"><div><span class="eyebrow">{{ t('hooks.eyebrow') }}</span><h1>{{ t('hooks.title') }}</h1></div><button class="button" @click="fresh">{{ t('hooks.new') }}</button></header>
    <div class="privilege-warning"><strong>⚠ {{ t('hooks.trusted') }}</strong><span>{{ t('hooks.trustedHint') }}</span></div>
    <div class="hooks-layout">
      <aside class="panel hook-list"><button v-for="hook in hooks" :key="hook.id" :class="{active:selectedId===hook.id}" @click="select(hook.id)"><span :class="['status',{online:hook.enabled}]">{{ hook.enabled?t('common.online'):t('common.parked') }}</span><strong>{{ hook.name }}</strong><small>{{ t('hooks.revision',{revision:hook.revision}) }}</small></button><p v-if="!hooks.length" class="empty text-xs">{{ t('hooks.new') }}</p></aside>
      <section class="panel editor-panel">
        <div class="form-grid"><label class="field"><span>{{ t('hooks.name') }}</span><input v-model="form.name" class="input" required /></label><label class="field"><span>{{ t('hooks.vehicle') }}</span><select v-model="form.vehicle_id" class="select"><option :value="null">{{ t('hooks.allVehicles') }}</option><option v-for="vehicle in vehicles" :key="vehicle.id" :value="vehicle.id">{{ vehicle.name }}</option></select></label><label class="field"><span>{{ t('hooks.description') }}</span><input v-model="form.description" class="input" /></label><label class="field"><span>{{ t('hooks.timeout') }}</span><input v-model="form.timeout_seconds" class="input" type="number" min="1" max="120" /></label></div>
        <label class="toggle"><input v-model="form.enabled" type="checkbox" /><span>{{ t('hooks.enabled') }}</span></label>
        <div class="field"><span>{{ t('hooks.source') }}</span><CodeEditor v-model="form.source" /></div>
        <p v-if="error" class="error">{{ error }}</p><div class="form-actions"><button class="button" @click="save">{{ saved?'✓':t('common.save') }}</button><button v-if="selected" class="button secondary" :disabled="testing" @click="testHook">{{ t('hooks.test') }}</button></div>
        <p v-if="selected" class="side-effect-warning">{{ t('hooks.sideEffectWarning') }}</p>
        <details v-if="revisions.length" class="revision-list"><summary>{{ t('hooks.revisions') }}</summary><div><button v-for="revision in revisions" :key="revision.id" class="button secondary text-xs" :disabled="revision.revision===selected?.revision" @click="restoreRevision(revision.revision)">{{ t('hooks.restoreRevision',{revision:revision.revision}) }}</button></div></details>
      </section>
    </div>
    <section v-if="selected" class="panel table-wrap mt-4"><h2 class="px-5 pt-4 text-base">{{ t('hooks.executions') }}</h2><table class="table"><thead><tr><th>{{ t('hooks.status') }}</th><th>{{ t('hooks.duration') }}</th><th>{{ t('hooks.logs') }}</th></tr></thead><tbody><tr v-for="execution in executions" :key="execution.id"><td><span :class="['status',{online:execution.status==='success'}]">{{ execution.status }}</span></td><td class="mono">{{ execution.duration_seconds===null?'—':`${Math.round(execution.duration_seconds*1000)} ms` }}</td><td><details><summary>{{ execution.logs.length }} / {{ execution.error?'error':'' }}</summary><pre class="execution-output">{{ execution.error||JSON.stringify(execution.logs,null,2) }}</pre></details></td></tr></tbody></table></section>
    <section class="panel panel-pad mt-4"><span class="eyebrow">{{ t('hooks.secrets') }}</span><p class="muted text-xs">{{ t('hooks.secretsHint') }}</p><form class="flex flex-wrap gap-2" @submit.prevent="storeSecret"><input v-model="secretName" class="input max-w-60" placeholder="gate_token" pattern="[A-Za-z][A-Za-z0-9_.-]*" required /><input v-model="secretValue" class="input max-w-80" type="password" placeholder="••••••••" required /><button class="button">{{ t('common.save') }}</button></form><ul class="secret-list"><li v-for="secret in secrets" :key="secret.id"><strong class="mono">{{ secret.name }}</strong><span>{{ secret.masked }}</span><button class="icon-button" @click="removeSecret(secret.name)">×</button></li></ul></section>
  </div>
</template>

<style scoped>
.privilege-warning{display:flex;gap:10px;align-items:center;padding:11px 14px;margin-bottom:14px;border:1px solid color-mix(in srgb,var(--warning) 42%,var(--line));border-left:4px solid var(--warning);background:color-mix(in srgb,var(--warning) 7%,transparent);font:400 9px "IBM Plex Sans",sans-serif}.privilege-warning strong{color:var(--warning);font:500 8px "IBM Plex Mono",monospace;white-space:nowrap;text-transform:uppercase}.privilege-warning span{color:var(--muted)}.hooks-layout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:13px}.hook-list{height:max-content;padding:0;overflow:hidden}.hook-list button{position:relative;width:100%;display:grid;grid-template-columns:1fr auto;gap:6px;padding:13px;color:var(--text);background:transparent;border:0;border-bottom:1px solid var(--line);text-align:left;cursor:pointer}.hook-list button:hover,.hook-list button.active{background:var(--petrol-soft)}.hook-list button.active::before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--signal)}.hook-list button strong{grid-column:1/-1;font:600 16px "Barlow Condensed",sans-serif;text-transform:uppercase}.hook-list button small{color:var(--muted);font:400 7px "IBM Plex Mono",monospace}.editor-panel{display:grid;gap:16px;padding:20px;border-radius:5px}.toggle{display:flex;align-items:center;gap:8px;font-size:11px}.side-effect-warning{margin:0;color:var(--warning);font:400 8px/1.5 "IBM Plex Mono",monospace}.revision-list{color:var(--muted);font-size:10px}.revision-list div{display:flex;flex-wrap:wrap;gap:6px;margin-top:9px}.execution-output{max-width:700px;color:var(--danger);font-size:9px;white-space:pre-wrap}.secret-list{list-style:none;padding:0;margin:18px 0 0;display:grid;gap:1px}.secret-list li{display:grid;grid-template-columns:1fr auto 30px;align-items:center;padding:10px 12px;background:var(--panel-2);border-left:2px solid var(--line-strong);font-size:10px}.secret-list span{color:var(--muted)}@media(max-width:800px){.hooks-layout{grid-template-columns:1fr}.hook-list{display:flex;overflow:auto}.hook-list button{min-width:170px;border-right:1px solid var(--line)}.privilege-warning{align-items:flex-start;flex-direction:column}}
</style>
